torque/audits/urls.py
# Core Django imports
from django.urls import path

# This project apps imports
from . import views

app_name = 'audits'

urlpatterns = [
    # test ex: /audits/ne_bogus/5/
    path('ne_bogus/<int:ne_id>/',
        views.ne_bogus, name='ne_bogus'
    ),

    # ex: /audits/ne_all/5/
    path('ne_all/<int:ne_id>/',
        views.ne_all, name='ne_all'
    ),

    # ex: /audits/ne_chassis_alarms/5/
    path('ne_chassis_alarms/<int:ne_id>/',
        views.ne_chassis_alarms, name='ne_alarms'
    ),

    # ex: /audits/ne_duplicate_ip/5/
    path('ne_duplicate_ip/<int:ne_id>/',
        views.ne_duplicate_ip, name='ne_duplicate_ip'
    ),

    # ex: /audits/ne_ibgp/5/
    path('ne_ibgp/<int:ne_id>/',
        views.ne_ibgp, name='ne_ibgp'
    ),

    # ex: /audits/ne_intopticdiag/5/
    path('ne_intopticdiag/<int:ne_id>/',
        views.ne_intopticdiag, name='ne_intopticdiag'
    ),

    # ex: /audits/ne_isis/5/
    path('ne_isis/<int:ne_id>/',
        views.ne_isis, name='ne_isis'
    ),

    # ex: /audits/ne_keywords/5/
    path('ne_keywords/<int:ne_id>/',
        views.ne_keywords, name='ne_keywords'
    ),

    # ex: /audits/ne_lldp/5/
    path('ne_lldp/<int:ne_id>/',
        views.ne_lldp, name='ne_lldp'
    ),

    # ex: /audits/ne_nni_description/5/
    path('ne_nni_description/<int:ne_id>/',
        views.ne_nni_description, name='ne_nni_description'
    ),

    # ex: /audits/ne_os/5/
    path('ne_os/<int:ne_id>/',
        views.ne_os, name='ne_os'
    ),

    # ex: /audits/ne_phyport/5/
    path('ne_phyport/<int:ne_id>/',
        views.ne_phyport, name='ne_phyport'
    ),

    # ex: /audits/ne_transceiver/5/
    path('ne_transceiver/<int:ne_id>/',
        views.ne_transceiver, name='ne_transceiver'
    ),

]

torque/core/urls.py
# Core Django imports
from django.conf.urls import url

# This project apps imports
from . import views

app_name = 'core'
urlpatterns = [
    # ex: /core/about/
    url(r'^about/$', views.about, name='about'),

    # ex: /core/features/
    url(r'^features/$', views.features, name='features'),

    # ex: /core/known_bugs/
    url(r'^known_bugs/$', views.known_bugs, name='known_bugs'),
]

torque/inventories/urls.py
# Core Django imports
from django.urls import path

# This project apps imports
from . import views

app_name = 'inventories'

urlpatterns = [

    # This is the landing page
    # /inventories/
    path('', views.ne_list, name='index'),

    # ex: /inventories/circuit/
    path('circuit/', views.circuit_list, name='circuit_list'),

    # ex: /inventories/ne/
    path('ne/', views.ne_list, name='ne_list'),

    # ex: /inventories/ne/5/
    path('ne/<int:pk>/', views.ne_detail, name='ne_detail'),

]

torque/torque/urls.py
# Core Django imports
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

# Third-party app imports
from rest_framework_swagger.views import get_swagger_view


schema_view = get_swagger_view(title='Torque API')


urlpatterns = [
    # Django built-in admin site
    path('admin/', admin.site.urls),

    # Django REST Framework, http://www.django-rest-framework.org/
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # Django REST Swagger, https://django-rest-swagger.readthedocs.io/en/latest/
    url(r'^api-doc/', schema_view),

    # This project apps
    path('audits/', include('audits.urls')),
    path('api/v1/', include('apiv1.urls')),
    path('core/', include('core.urls')),
    path('catalogues/', include('catalogues.urls')),
    path('inventories/', include('inventories.urls')),
]


# Use static() to add url mapping to serve static files during development (only)
# https://docs.djangoproject.com/en/2.0/howto/static-files/#serving-static-files-during-development
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# This is the landing page. Redirects the base URL '/' (or empty) to '/inventories/'.
# Taken from https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/skeleton_website
# Leave the first parameter of the path function empty to imply '/'.
# If you write the first parameter as '/' Django will give you the following warning:
# ?: (urls.W002) Your URL pattern '/' has a route beginning with a '/'.
# Remove this slash as it is unnecessary.
from django.views.generic.base import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/inventories/', permanent=True)),
]

torque/inventories/models.py
'''
Notes on Django model fields:
https://docs.djangoproject.com/en/1.11/ref/models/fields/#unique

null, default is False
blank, default is False

unique. When unique is True, you don’t need to specify db_index,
because unique implies the creation of an index.

To do:
'''

# Core Django imports
from django.db import models
from django.urls import reverse #Used to generate URLs by reversing the URL patterns



class Circuit(models.Model):
    supplier = models.ForeignKey(
        'catalogues.supplier',
        on_delete = models.PROTECT,
        related_name = "supplier",
    )
    circuit_id = models.CharField(max_length = 50, 
        unique = True,
        verbose_name = "Circuit ID",
        help_text = "Unique identifier provided by the supplier for this circuit. Has to be unique across all the circuits in the database."
    )
    a_end_description = models.CharField(max_length = 255,
        blank = True
    )
    b_end_description = models.CharField(max_length = 255,
        blank = True
    )
    circuit_type = models.CharField(max_length = 255, 
        blank = True
    )
    circuit_info = models.CharField(max_length = 255,
        blank = True
    )

    def __str__(self):
        """
        String for representing the Circuit object (in Admin site etc.)
        """
        return self.circuit_id


class OsCredential(models.Model):
    username = models.CharField(max_length = 64, 
        unique = True,
        help_text = "Username to authenticate with in this NE."
    )
    password = models.CharField(max_length=64,
        help_text = "Password to authenticate with in this NE."
    )

    class Meta:
        """
        Default ordering of records returned when querying the model.
        """
        ordering = ['username']
        verbose_name = "Operating System credentials"

    def __str__(self):
        """
        String for representing the OsCredential object (in Admin site etc.)
        """
        return self.username


class Ne(models.Model):
    fqdn = models.CharField(max_length = 255,
        unique = True,
        verbose_name = "FQDN",
        help_text = "As {hostname}.{domain/sub-domain}.{tld}; e.g. 'core1-lim1.nn.hea.net'."
    )
    os_credential = models.ForeignKey(
        OsCredential,
        on_delete = models.SET_NULL, 
        null = True,
        blank = True, 
        verbose_name = "OS Credentials",
        help_text = "Username to authenticate with in this NE."
    )
    # when doing: python manage.py makemigrations
    # WARNINGS:
    # inventory.Ne.nni_neighbor: (fields.W340) null has no effect 
    # on ManyToManyField.
    nni_neighbors = models.ManyToManyField(
        'self', 
        blank = True,
        verbose_name = 'NNI neighbors',
        help_text = "What other NE is this NE connected to. There is only need to create the relationship in one of the NE, then the system will automatically create the reverse relationship."
    )

    class Meta:
        """
        Default ordering of records returned when querying the model.
        """
        ordering = ['fqdn']
        verbose_name = "Network Element"
        verbose_name_plural = "Network Elements"

    def __str__(self):
        """
        String for representing the Ne object (in Admin site etc.)
        """
        return self.fqdn

    def get_absolute_url(self):
        """
        Returns the url to access a particular instance of Ne.

        When this method is defined in model.py, Django automatically adds a 
        "View on Site" button to the model's record editing screens in the 
        Admin site.
        """
        return reverse('inventories:ne_detail', args=[str(self.id)])


'''
class AdminStatus(models.Model):
    status = models.CharField(max_length = 255,
        unique = True,
        verbose_name = "Operational status"
    )

    class Meta:
        ordering = ['status']
        verbose_name = "Status"
        verbose_name = "Statuses"

    def __str__(self):
        return self.fqdn
'''

torque/inventories/views.py
# Core Django imports
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect

# This project apps imports
from inventories.models import Circuit
from inventories.models import Ne


def circuit_list(request):
    context = {'bodymessage': "Circuits inventory"}
    context['circuit_list'] = Circuit.objects.all()
    return render(request, 'inventories/circuit_list.html', context)


def index(request):
    # take this as the landing page. For the moment redirect. 
    # At some point, a very simple page with 1-2 choices? dropdown?
    return redirect(ne_list)


def ne_list(request):
    context = {'bodymessage': "Inventory -> Index"}

    '''
    # This section works when settings DEBUG=True, but NOT when False!!!
    # maybe related to serving static files in productin??? Whitenoise package?
    import os, random
    gif_random = random.choice(os.listdir('static/gif'))
    print(gif_random)
    context['gif_random'] = gif_random
    '''
    import os, random
    from datetime import datetime
    random.seed(datetime.now())

    dir_parent = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    #print(dir_parent)
    dir_gif = os.path.join(dir_parent, 'static/gif')
    #print(dir_gif)
    gif_random = random.choice(os.listdir(dir_gif))
    #print(gif_random)
    context['gif_random'] = gif_random

    context['ne_all'] = Ne.objects.all()
    return render(request, 'inventories/ne_list.html', context)


def ne_detail(request, pk):
    context = {'bodymessage': "Inventory -> NE detail"}
    ne = get_object_or_404(Ne, pk=pk)
    context = {'bodymessage': "Details for " + ne.fqdn }
    context['ne'] = ne

    nni_neighbors = ne.nni_neighbors.all()
    context['nni_neighbors'] = nni_neighbors

    '''
    # for graphing, work in progress
    ne_params = get_me_ne_attributes(ne_id)
    nni_neighbors_expected = ne_params['nni_neighbors']
    print("nni_neighbors_expected")
    print(nni_neighbors_expected)
    hostname = ne.fqdn.split('.')[0]
    print("hostname")
    print(hostname)
    from core.utils import graph_ne_nni
    graph_ne_nni.graph_ne_nni(hostname, nni_neighbors_expected)
    context['img_name'] = "nnis_" + hostname + ".svg"
    '''

    ''' to show a random gif while the audit report loads '''
    import os, random
    from datetime import datetime
    random.seed(datetime.now())
    dir_parent = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    dir_gif = os.path.join(dir_parent, 'static/gif')
    gif_random = random.choice(os.listdir(dir_gif))
    context['gif_random'] = gif_random

    return render(request, 'inventories/ne_detail.html', context)

torque/inventories/templates/inventories/audit_report.html
{% extends 'base.html' %}

{% block content %}

  <!-- begin, Heading -->
  <!--
  <div class="alert alert-info">
    <strong><h4 class="text-warning">{{ bodymessage }}</h4></strong>
    <a href="{% url 'inventory:ne_list' %}">Inventory</a>
    <p>Report timestamp: {{ report_timestamp|date:"l, j M Y H:i"}}</p>
    <p>Report timestamp: {% now "l, j M Y H:i" %}</p>
    <p>Overall Audit Result: {{ overall_audit_result }}</p>
  </div>
  -->

  <!-- begin, Heading -->
{% if overall_audit_result %}
    {% if overall_audit_result == "FAIL" %}
    <div class="alert alert-danger" role="alert">
    {% endif %}
    {% if overall_audit_result == "PASS" %}
    <div class="alert alert-success" role="alert">
    {% endif %}

  <!--<div class="alert alert-info">-->
    <strong><h4 class="text-warning">{{ bodymessage }}</h4></strong>
    <a href="{% url 'inventory:ne_list' %}">Go back to Inventory</a>
    <p></p>
    <a href="{% url 'inventory:detail' ne_id %}">Go back to {{ ne_fqdn }}</a>
    <p>Report timestamp: {{ report_timestamp|date:"l, j M Y H:i"}}</p>
    <!--<p>Report timestamp: {% now "l, j M Y H:i" %}</p>
    -->
    <p>Overall Audit Result: {{ overall_audit_result }}</p>
  </div>
{% endif %}

  <!--
  <div class="table-responsive">
  <table class="alert alert-info">
    <thead>
      <tr>
        <td>
          <strong><h4 class="text-warning">{{ bodymessage }}</h4></strong>
        </td>
        <td>
          <p>Report timestamp: {{ report_timestamp|date:"l, j M Y H:i"}}</p>
          <a href="{% url 'inventory:ne_list' %}">Inventory</a>
        </td>
      </tr>
    </thead>
  </table>
  </div>
  -->


  <!--
  <div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <strong><h4 class="text-warning">{{ bodymessage }}</h4></strong>
        </td>
        <td>
          <a href="{% url 'inventory:ne_list' %}">Inventory</a>
        </td>
      </tr>
    </tbody>
  </table>
  </div>
  -->


  <!-- begin, django messages, if there are any -->
  {% if messages %}
    {% for message in messages %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
    <div class="alert alert-info" role="alert">
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
    <div class="alert alert-success" role="alert">
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
    <div class="alert alert-warning" role="alert">
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
    <div class="alert alert-danger" role="alert">
    {% endif %}

      <strong>{{ message }}</strong>
    </div>

    {% endfor %}
  {% endif %}
  <!-- end, django messages, if there are any -->


  <!-- begin, Table with results -->
  <div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for l in audit_report %}
        <tr>
		  <td>{{ l }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  </div>
  <!-- end, Table with results -->


  <!-- begin, Foot -->
  <div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <a href="{% url 'inventory:ne_list' %}">Go back to Inventory</a>
        </td>
      </tr>
    </tbody>
  </table>
  </div>
  <!-- end, Foot -->


{% endblock content %}

torque/inventories/templates/inventories/audit_report_email.html
  <!--Heading, begin -->
{% if overall_audit_result %}
    {% if overall_audit_result == "FAIL" %}
    <div class="alert alert-danger" role="alert">
    {% endif %}
    {% if overall_audit_result == "PASS" %}
    <div class="alert alert-success" role="alert">
    {% endif %}

  <!--<div class="alert alert-info">-->
    <strong><h4 class="text-warning">{{ bodymessage }}</h4></strong>
    <a href="{% url 'inventories:ne_list' %}">Back to Inventory</a>
    <p></p>
    <a href="{% url 'inventories:ne_detail' ne_id %}">Back to {{ ne_fqdn }}</a>
    <p>Report timestamp: {{ report_timestamp|date:"l, j M Y H:i"}}</p>
    <p>Overall Audit Result: {{ overall_audit_result }}</p>
  </div>
{% endif %}
<!-- Heading, end -->



  <!-- begin, django messages, if there are any -->
  {% if messages %}
    {% for message in messages %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
    <div class="alert alert-info" role="alert">
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
    <div class="alert alert-success" role="alert">
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
    <div class="alert alert-warning" role="alert">
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
    <div class="alert alert-danger" role="alert">
    {% endif %}

      <strong>{{ message }}</strong>
    </div>

    {% endfor %}
  {% endif %}
  <!-- end, django messages, if there are any -->

  <!-- begin, Table with results -->
  {% if report_fail|length > 0%}
<div class="alert alert-danger" role="alert">
  <div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for l in report_fail %}
        <tr>
          <td>{{ l }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  </div>
</div>
{% endif %}
  <!-- end, Table with results -->

  <!-- begin, Table with results -->
  {% if report_warning|length > 0%}
<div class="alert alert-warning" role="alert">
  <div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for l in report_warning %}
        <tr>
          <td>{{ l }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  </div>
</div>
{% endif %}
  <!-- end, Table with results -->

  <!-- begin, Table with results -->
  {% if report_pass|length > 0%}
<div class="alert alert-success" role="alert">
  <div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for l in report_pass %}
        <tr>
          <td>{{ l }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  </div>
</div>
{% endif %}
  <!-- end, Table with results -->

torque/inventories/templates/inventories/ne_detail.html
{% extends 'base.html' %}

{% block content %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
    // this works, this is the baseline!!
    // https://www.w3schools.com/jsref/prop_style_display.asp
    $(".myclass").click(function(){
        //document.getElementById("mydiv2").style.visibility = "visible";
        document.getElementById("mydiv2").style.display = "block";
        document.getElementById("myheader").style.display = "none";
        document.getElementById("mytable").style.display = "none";
        document.getElementById("mytable2").style.display = "none";
        document.getElementById("mytable3").style.display = "none";
    });

    // Works. On click, the original page becomes transparent and a new image
    // (hidden up to them) does show up.
    // https://www.w3schools.com/jsref/prop_style_opacity.asp
    //$(".myclass").click(function(){
    //    document.getElementById("mydiv2").style.display = "block";
    //   document.getElementById("myheader").style.opacity = "0.5";
    //    document.getElementById("mytable").style.opacity = "0.5";
    //});
});
</script>

<div id="mydiv2" style="display: none;">
  {% load staticfiles%}
  <img class="img-rounded" src="/static/gif/{{ gif_random }}" id="mygif2" style="display: block; margin- left: auto; margin-right: auto; vertical-align: middle; width: 80%; height: auto;">
</div>

<!--
{% load staticfiles %}
<img class="img-rounded" src="/static/{{ img_name }}" style="width: 40%; height: auto;">
-->

  <div class="alert alert-info" id="myheader">
    <h3 class="sub-header">{{ bodymessage }}</h4>
    <a href="{% url 'inventories:ne_list' %}">Back to Inventory</a>
  </div>

<!-- https://bootstrapdocs.com/v3.3.6/docs/css/#grid -->
<div class="container-fluid"><!--Grid container, begin--> 
<div class="row"><!-- Row, begin -->
<div class="col-xs-6"><!-- column, begin -->
  <div class="table-responsive" id="mytable">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>These are my NNI Neighbors</th>
      </tr>
    </thead>

	<tbody>
	{% for nni_neighbor in nni_neighbors %}
	  <tr>
        <td>
          <a href="{% url 'inventories:ne_detail' nni_neighbor.id %}">{{ nni_neighbor.fqdn }}</a>
        </td>
      </tr>
	{% endfor %}
	</tbody>
  </table>
  </div>
</div><!-- column, end -->

<div class="col-xs-6"><!-- column, begin -->
  <!--  
  {% load staticfiles %}
  <img class="img-rounded" src="/static/{{ img_name }}" style="width: 60%; height: auto;">
  <p></p>
  <p></p>
  --> 
</div><!-- column, end -->


</div><!-- Row, end -->
</div><!--Grid container, end-->



  <!-- django messages, if there are any -->
  {% if messages %}
    {% for message in messages %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
    <div class="alert alert-info" role="alert">
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
    <div class="alert alert-success" role="alert">
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
    <div class="alert alert-warning" role="alert">
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
    <div class="alert alert-danger" role="alert">
    {% endif %}

      <strong>{{ message }}</strong>
    </div>

    {% endfor %}
  {% endif %}


  <!-- mark, this goes to the audits app -->
  <div class="table-responsive" id="mytable2">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>FQDN</th>
        <th>Audit</th>
        <th>Audit</th>
        <th>Audit</th>
        <th>Audit</th>
        <th>Audit</th>
        <th>Audit</th>
        <th>Audit</th>
        <th>Audit</th>
        <th>Audit</th>
        <th>Audit</th>
        <th>Audit</th>
        <th>Audit</th>
        <th>Audit</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td>
          <a href="{% url 'inventories:ne_detail' ne.id %}">{{ ne.fqdn }}</a>
        </td>
        <td>
          <a class="myclass" href="{% url 'audits:ne_all' ne.id %}">All</a>
        </td>
        <td>
          <a class="myclass" href="{% url 'audits:ne_bogus' ne.id %}">Piggies in Space</a>
        </td>
        <td>
          <a class="myclass" href="{% url 'audits:ne_os' ne.id %}">OS</a>
        </td>
        <td>
          <a class="myclass" href="{% url 'audits:ne_keywords' ne.id %}">Commands and Files</a>
        </td>
        <td>
          <a class="myclass" href="{% url 'audits:ne_alarms' ne.id %}">Chassis Alarms</a>
        </td>
        <td>
          <a class="myclass" href="{% url 'audits:ne_transceiver' ne.id %}">Transceivers</a>
        </td>
        <td>
          <a class="myclass" href="{% url 'audits:ne_intopticdiag' ne.id %}">Optical diagnostics</a>
        </td>
        <td>
          <a class="myclass" href="{% url 'audits:ne_phyport' ne.id %}">Physical ports</a>
        </td>
        <td>
          <a class="myclass" href="{% url 'audits:ne_nni_description' ne.id %}">NNI description</a>
        </td>
        <td>
          <a class="myclass" href="{% url 'audits:ne_lldp' ne.id %}">LLDP</a>
        </td>
        <td>
          <a class="myclass" href="{% url 'audits:ne_duplicate_ip' ne.id %}">IP Consistency</a>
        </td>
        <td>
          <a class="myclass" href="{% url 'audits:ne_isis' ne.id %}">IS-IS</a>
        </td>
        <td>
          <a class="myclass" href="{% url 'audits:ne_ibgp' ne.id %}">iBGP</a>
        </td>
      </tr>
    </tbody>
  </table>
  </div>


{% endblock content %}

torque/inventories/templates/inventories/ne_list.html
{% extends 'base.html' %}

{% block content %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
	$("#mydiv1").hide();
	$("#myhref").click(function(){
		$("#mydiv1").show();
	});

    $("#myhref").click(function(){
        //document.getElementById("mydiv2").style.visibility = "visible";
        document.getElementById("mydiv2").style.display = "block";
        document.getElementById("myheader").style.display = "none";
        document.getElementById("mytable").style.display = "none";
    });

    // This works, this is the baseline!!
    // https://www.w3schools.com/jsref/prop_style_display.asp
    // On click, the original page (ids: "myheader" and "mytable") and 
    // an image appears (id: "mydiv2")
    $(".myclass").click(function(){
        //document.getElementById("mydiv2").style.visibility = "visible";
        document.getElementById("mydiv2").style.display = "block";
        document.getElementById("myheader").style.display = "none";
        document.getElementById("mytable").style.display = "none";
    });

    // Works. On click, the original page becomes transparent and a new image
    // (hidden up to them) does show up.
    // https://www.w3schools.com/jsref/prop_style_opacity.asp
    //$(".myclass").click(function(){
    //    document.getElementById("mydiv2").style.display = "block";
    //   document.getElementById("myheader").style.opacity = "0.5";
    //    document.getElementById("mytable").style.opacity = "0.5";
    //});
});
</script>
<!--
<div id="mydiv1">
  <img src="/static/gif/ballerina_1.gif" id="mygif" style="width: 20%; height: 200%">
</div>
-->

<!--<div id="mydiv2" style="visibility: hidden;">-->
<div id="mydiv2" style="display: none;">
  <p></p>
  {% load static %}
  <!--<img class="img-rounded" src="{% static "gif/Muybridge_race_horse_animated.gif" %}" id="mygif2" style="display: block; margin-left: auto; margin-right: auto; vertical-align: middle; width: 80%; height: auto;">-->
  <img class="img-rounded" src="/static/gif/{{ gif_random }}" id="mygif2" style="display: block; margin- left: auto; margin-right: auto; vertical-align: middle; width: 80%; height: auto;">
</div>


<div class="alert alert-info" role="alert" id="myheader">
  <h6>You know why you are here. <strong>HIT ME!!</strong></h6>
</div>


<div class="table-responsive" id="mytable">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>FQDN</th>
        <th>Audit (Expect between 60 and 90 sec for ACX2200)</th>
      </tr>
    </thead>
    <tbody>
      {% for ne in ne_all %}
        <tr>
          <td>
            <a href="{% url 'inventories:ne_detail' ne.pk %}">{{ ne.fqdn }}</a>
          </td>
          <td>
            <button type="button" style="background-color:#FFB81C" class="btn btn-warning btn-circle">
              <a class="myclass" href="{% url 'audits:ne_all' ne.pk %}">Full audit</a>
            </button>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  </div>

{% endblock content %}