torque/core/urls.py
# Core Django imports
from django.conf.urls import url

# This project apps imports
from . import views

app_name = 'core'
urlpatterns = [
    # ex: /core/about/
    url(r'^about/$', views.about, name='about'),

    # ex: /core/features/
    url(r'^features/$', views.features, name='features'),

    # ex: /core/known_bugs/
    url(r'^known_bugs/$', views.known_bugs, name='known_bugs'),
]

torque/inventories/urls.py
# Core Django imports
from django.urls import path

# This project apps imports
from . import views

app_name = 'inventories'

urlpatterns = [

    # This is the landing page
    # /inventories/
    path('', views.ne_list, name='index'),

    # ex: /inventories/circuit/
    path('circuit/', views.circuit_list, name='circuit_list'),

    # ex: /inventories/ne/
    path('ne/', views.ne_list, name='ne_list'),

    # ex: /inventories/ne/5/
    path('ne/<int:pk>/', views.ne_detail, name='ne_detail'),

]

torque/torque/urls.py
# Core Django imports
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

# Third-party app imports
from rest_framework_swagger.views import get_swagger_view


schema_view = get_swagger_view(title='Torque API')


urlpatterns = [
    # Django built-in admin site
    path('admin/', admin.site.urls),

    # Django REST Framework, http://www.django-rest-framework.org/
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # Django REST Swagger, https://django-rest-swagger.readthedocs.io/en/latest/
    url(r'^api-doc/', schema_view),

    # This project apps
    path('audits/', include('audits.urls')),
    path('api/v1/', include('apiv1.urls')),
    path('core/', include('core.urls')),
    path('catalogues/', include('catalogues.urls')),
    path('inventories/', include('inventories.urls')),
]


# Use static() to add url mapping to serve static files during development (only)
# https://docs.djangoproject.com/en/2.0/howto/static-files/#serving-static-files-during-development
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# This is the landing page. Redirects the base URL '/' (or empty) to '/inventories/'.
# Taken from https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/skeleton_website
# Leave the first parameter of the path function empty to imply '/'.
# If you write the first parameter as '/' Django will give you the following warning:
# ?: (urls.W002) Your URL pattern '/' has a route beginning with a '/'.
# Remove this slash as it is unnecessary.
from django.views.generic.base import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/inventories/', permanent=True)),
]

torque/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above meta tags *must* come first in the head; any other head 
    content must come *after* these tags -->

    <meta name="description" content="Audits a Juniper NE for consistency in its configration">
    <meta name="keywords" content="Audit, junos-eznc">
    <meta name="author" content="HEAnet GLC">

    <!--This is the favicon-->
    <link rel="icon" href="{% static 'assets/img/circulo_naranja.png' %}">

    <!-- putting <title> inside a block template tag results in a default title 
    that will be rendered by "default" unless passed on from the view -->
    {% block title %}<title>Torque</title>{% endblock title %}

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Bootstrap specific, in this case Sticky footer with fixed navbar -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/sticky-footer-navbar.css' %}">


    <!-- Google Analytics, begin -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      <!-- this is the unique ID for this site from a Google Analytics point of view -->
      ga('create', 'UA-100959520-2', 'auto');
      ga('send', 'pageview');
    </script>
    <!-- Google Analytics, end -->

  </head>


  <body>

    <header>
      <!-- Fixed navbar -->
	  <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <!--<a class="navbar-brand" href="#">Torque</a>-->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">

            <li class="nav-item">
            <!--<li class="nav-item active">-->
              <!--<a class="nav-link" href="{% url 'inventories:ne_list' %}">NE <span class="sr-only">(current)</span></a>-->
              <a class="nav-link" href="{% url 'inventories:ne_list' %}">NE</a>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Inventories
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'inventories:ne_list' %}">NE</a>
                <a class="dropdown-item" href="{% url 'inventories:circuit_list' %}">Circuits</a>
              </div>
            </li>


            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                API
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/api/v1/">API GUI</a>
                <a class="dropdown-item" href="/api-doc/">API documentation (swagger/OpenAPI)</a>
              </div>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Documentation
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'core:about' %}">About</a>
                <a class="dropdown-item" href="{% url 'core:features' %}">Features</a>
              <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'core:known_bugs' %}">Known Bugs</a>
              </div>
            </li>

          </ul>
        </div>
      </nav>
    </header>


    <div class="container"> <!-- page content, begin -->
      {% block content %}
        <!-- the other templates will insert content here -->
      {% endblock content %}
    </div> <!-- page content, end -->


	<!--
    <footer class="footer">
      <div class="container">
        <p class="text-muted">Place sticky footer content here.</p>
      </div>
    </footer>
	-->


    <!-- Bootstrap core JavaScript
    ====================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <!-- jQuery, from either a DCN or locally -->
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>-->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>

    <!-- Bootstrap -->
    <script src="{% static 'assets/js/vendor/jquery-slim.min.js' %}"></script>
	<script src="{% static 'assets/js/vendor/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

  </body>
</html>

torque/templates/sticky-footer-navbar.html
{% load staticfiles%}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <!--
    <title>Sticky Footer Navbar Template for Bootstrap</title>
    -->
    <title>Torque</title>

    <!-- Bootstrap core CSS -->
    <!--
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">
    -->
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}" />

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!--
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
    -->
    <link rel="stylesheet" type="text/css" href="{% static "assets/css/ie10-viewport-bug-workaround.css" %}" />

    <!-- Custom styles for this template -->
    <!--
    <link href="sticky-footer-navbar.css" rel="stylesheet">
    -->
    <link rel="stylesheet" type="text/css" href="{% static "css/sticky-footer-navbar.css" %}" />

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!--
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
    -->
    <script src="{% static "assets/js/ie-emulation-modes-warning.js" %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <!--
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">You know why you are here. HIT ME!!</a>
        </div>
        -->

        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <!--
            <li class="active"><a href="#">Home</a></li>
            -->
            <!--
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            -->
            <!-- begin, dropdown
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
            end, dropdown -->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <!-- Begin page content -->
    <!-- begin, this is the body -->
    <div class="container">
    <!--
      <div class="page-header">
        <h1>Sticky footer with fixed navbar</h1>
      </div>
      <p class="lead">Pin a fixed-height footer to the bottom of the viewport in desktop browsers with this custom HTML and CSS. A fixed navbar has been added with <code>padding-top: 60px;</code> on the <code>body &gt; .container</code>.</p>
      <p>Back to <a href="../sticky-footer">the default sticky footer</a> minus the navbar.</p>
      -->

      {% block content %}
      {% endblock content %}


    </div>
    <!-- end, this is the body -->

    <!-- 
    <footer class="footer">
      <div class="container">
        <p class="text-muted">Place sticky footer content here.</p>
      </div>
    </footer>
    -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <!--
    <script src="../../dist/js/bootstrap.min.js"></script>
    -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!--
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
    -->
    <script src="{% static "assets/js/ie10-viewport-bug-workaround.js" %}"></script>
  </body>
</html>

torque/templates/sticky-footer.html
{% load staticfiles%}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <!--
    <title>Sticky Footer Navbar Template for Bootstrap</title>
    -->
    <title>Torque</title>

    <!-- Bootstrap core CSS -->
    <!--
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">
    -->
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}" />

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!--
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
    -->
    <link rel="stylesheet" type="text/css" href="{% static "assets/css/ie10-viewport-bug-workaround.css" %}" />

    <!-- Custom styles for this template -->
    <!--
    <link href="sticky-footer-navbar.css" rel="stylesheet">
    -->
    <link rel="stylesheet" type="text/css" href="{% static "css/sticky-footer-navbar.css" %}" />

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!--
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
    -->
    <script src="{% static "assets/js/ie-emulation-modes-warning.js" %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Begin page content -->
    <div class="container">
      <div class="page-header">
        <h1>Sticky footer</h1>
      </div>
      <p class="lead">Pin a fixed-height footer to the bottom of the viewport in desktop browsers with this custom HTML and CSS.</p>
      <p>Use <a href="../sticky-footer-navbar">the sticky footer with a fixed navbar</a> if need be, too.</p>

      {% block content %}
      {% endblock content %}

    </div>

	<!--
    <footer class="footer">
      <div class="container">
        <p class="text-muted">Place sticky footer content here.</p>
      </div>
    </footer>
	-->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!--<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>-->
	<script src="{% static "assets/js/ie10-viewport-bug-workaround.js" %}"></script>
  </body>
</html>