torque/audits/urls.py
# Core Django imports
from django.urls import path

# This project apps imports
from . import views

app_name = 'audits'

urlpatterns = [
    # test ex: /audits/ne_bogus/5/
    path('ne_bogus/<int:ne_id>/',
        views.ne_bogus, name='ne_bogus'
    ),

    # ex: /audits/ne_all/5/
    path('ne_all/<int:ne_id>/',
        views.ne_all, name='ne_all'
    ),

    # ex: /audits/ne_chassis_alarms/5/
    path('ne_chassis_alarms/<int:ne_id>/',
        views.ne_chassis_alarms, name='ne_alarms'
    ),

    # ex: /audits/ne_duplicate_ip/5/
    path('ne_duplicate_ip/<int:ne_id>/',
        views.ne_duplicate_ip, name='ne_duplicate_ip'
    ),

    # ex: /audits/ne_ibgp/5/
    path('ne_ibgp/<int:ne_id>/',
        views.ne_ibgp, name='ne_ibgp'
    ),

    # ex: /audits/ne_intopticdiag/5/
    path('ne_intopticdiag/<int:ne_id>/',
        views.ne_intopticdiag, name='ne_intopticdiag'
    ),

    # ex: /audits/ne_isis/5/
    path('ne_isis/<int:ne_id>/',
        views.ne_isis, name='ne_isis'
    ),

    # ex: /audits/ne_keywords/5/
    path('ne_keywords/<int:ne_id>/',
        views.ne_keywords, name='ne_keywords'
    ),

    # ex: /audits/ne_lldp/5/
    path('ne_lldp/<int:ne_id>/',
        views.ne_lldp, name='ne_lldp'
    ),

    # ex: /audits/ne_nni_description/5/
    path('ne_nni_description/<int:ne_id>/',
        views.ne_nni_description, name='ne_nni_description'
    ),

    # ex: /audits/ne_os/5/
    path('ne_os/<int:ne_id>/',
        views.ne_os, name='ne_os'
    ),

    # ex: /audits/ne_phyport/5/
    path('ne_phyport/<int:ne_id>/',
        views.ne_phyport, name='ne_phyport'
    ),

    # ex: /audits/ne_transceiver/5/
    path('ne_transceiver/<int:ne_id>/',
        views.ne_transceiver, name='ne_transceiver'
    ),

]

torque/core/urls.py
# Core Django imports
from django.conf.urls import url

# This project apps imports
from . import views

app_name = 'core'
urlpatterns = [
    # ex: /core/about/
    url(r'^about/$', views.about, name='about'),

    # ex: /core/features/
    url(r'^features/$', views.features, name='features'),

    # ex: /core/known_bugs/
    url(r'^known_bugs/$', views.known_bugs, name='known_bugs'),
]

torque/inventories/urls.py
# Core Django imports
from django.urls import path

# This project apps imports
from . import views

app_name = 'inventories'

urlpatterns = [

    # This is the landing page
    # /inventories/
    path('', views.ne_list, name='index'),

    # ex: /inventories/circuit/
    path('circuit/', views.circuit_list, name='circuit_list'),

    # ex: /inventories/ne/
    path('ne/', views.ne_list, name='ne_list'),

    # ex: /inventories/ne/5/
    path('ne/<int:pk>/', views.ne_detail, name='ne_detail'),

]

torque/torque/urls.py
# Core Django imports
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path

# Third-party app imports
from rest_framework_swagger.views import get_swagger_view


schema_view = get_swagger_view(title='Torque API')


urlpatterns = [
    # Django built-in admin site
    path('admin/', admin.site.urls),

    # Django REST Framework, http://www.django-rest-framework.org/
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # Django REST Swagger, https://django-rest-swagger.readthedocs.io/en/latest/
    url(r'^api-doc/', schema_view),

    # This project apps
    path('audits/', include('audits.urls')),
    path('api/v1/', include('apiv1.urls')),
    path('core/', include('core.urls')),
    path('catalogues/', include('catalogues.urls')),
    path('inventories/', include('inventories.urls')),
]


# Use static() to add url mapping to serve static files during development (only)
# https://docs.djangoproject.com/en/2.0/howto/static-files/#serving-static-files-during-development
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# This is the landing page. Redirects the base URL '/' (or empty) to '/inventories/'.
# Taken from https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/skeleton_website
# Leave the first parameter of the path function empty to imply '/'.
# If you write the first parameter as '/' Django will give you the following warning:
# ?: (urls.W002) Your URL pattern '/' has a route beginning with a '/'.
# Remove this slash as it is unnecessary.
from django.views.generic.base import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/inventories/', permanent=True)),
]

torque/audits/models.py
# Core Django imports
from django.db import models

torque/audits/views.py
# Core Django imports
from django.shortcuts import render

# This project apps imports
from audits.libs import audits_ne

def ne_bogus(request, ne_id):
    '''
    Calls a function in another "module"?. The function returns a dictionary
    and we render that dictionary.
    '''
    from audits.libs import audits_ne
    context = audits_ne.ne_audit_bogus(ne_id)
    return render(request, 'audits/audit_report_blocks.html', context)
    

def ne_all(request, ne_id):
    from audits.libs import audits_ne
    context = audits_ne.ne_audit_all(ne_id)
    return render(request, 'audits/audit_report_blocks.html', context)


def ne_chassis_alarms(request, ne_id):
    from audits.libs import audits_ne
    context = audits_ne.ne_audit_chassis_alarms(ne_id)
    return render(request, 'audits/audit_report_blocks.html', context)


def ne_duplicate_ip(request, ne_id):
    from audits.libs import audits_ne
    context = audits_ne.ne_audit_duplicate_ip(ne_id)
    return render(request, 'audits/audit_report_blocks.html', context)


def ne_ibgp(request, ne_id):
    from audits.libs import audits_ne
    context = audits_ne.ne_audit_ibgp(ne_id)
    return render(request, 'audits/audit_report_blocks.html', context)


def ne_intopticdiag(request, ne_id):
    from audits.libs import audits_ne
    context = audits_ne.ne_audit_intopticdiag(ne_id)
    return render(request, 'audits/audit_report_blocks.html', context)


def ne_isis(request, ne_id):
    from audits.libs import audits_ne
    context = audits_ne.ne_audit_isis(ne_id)
    return render(request, 'audits/audit_report_blocks.html', context)


def ne_keywords(request, ne_id):
    from audits.libs import audits_ne
    context = audits_ne.ne_audit_keywords(ne_id)
    return render(request, 'audits/audit_report_blocks.html', context)


def ne_lldp(request, ne_id):
    from audits.libs import audits_ne
    context = audits_ne.ne_audit_lldp(ne_id)
    return render(request, 'audits/audit_report_blocks.html', context)


def ne_nni_description(request, ne_id):
    from audits.libs import audits_ne
    context = audits_ne.ne_audit_nni_description(ne_id)
    return render(request, 'audits/audit_report_blocks.html', context)


def ne_os(request, ne_id):
    from audits.libs import audits_ne
    context = audits_ne.ne_audit_os(ne_id)
    return render(request, 'audits/audit_report_blocks.html', context)


def ne_phyport(request, ne_id):
    from audits.libs import audits_ne
    context = audits_ne.ne_audit_phyport(ne_id)
    return render(request, 'audits/audit_report_blocks.html', context)


def ne_transceiver(request, ne_id):
    from audits.libs import audits_ne
    context = audits_ne.ne_audit_transceiver(ne_id)
    return render(request, 'audits/audit_report_blocks.html', context)

torque/audits/templates/audits/audit_report_blocks.html
{% extends 'base.html' %}

{% block content %}


<!-- begin, Heading -->
{% if overall_audit_result %}
  {% if overall_audit_result == "FAIL" %}
  <div class="alert alert-danger" role="alert">
  {% endif %}
  {% if overall_audit_result == "PASS" %}
  <div class="alert alert-success" role="alert">
  {% endif %}
  {% if overall_audit_result == "WARNING" %}
  <div class="alert alert-warning" role="alert">
  {% endif %}

    <strong><h4>{{ bodymessage }}</h4></strong>
    <a href="{% url 'inventories:ne_list' %}">Back to Inventory</a><br>
    <a href="{% url 'inventories:ne_detail' ne_id %}">Back to {{ ne_fqdn }}</a><br>
    Report timestamp: {{ report_timestamp|date:"l, j M Y H:i"}}<br>
    Overall Audit Result: {{ overall_audit_result }}<br>
  </div>
{% endif %}
<!-- end, Heading -->



  <!-- begin, django messages, if there are any -->
  {% if messages %}
    {% for message in messages %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
    <div class="alert alert-info" role="alert">
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
    <div class="alert alert-success" role="alert">
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
    <div class="alert alert-warning" role="alert">
    {% endif %}

    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
    <div class="alert alert-danger" role="alert">
    {% endif %}

      <strong>{{ message }}</strong>
    </div>

    {% endfor %}
  {% endif %}
  <!-- end, django messages, if there are any -->


<!-- begin, Table with FAIL results -->
{% if report_fail|length > 0%}
<div class="alert alert-danger" role="alert">
  <div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for l in report_fail %}
        <tr>
          <td>{{ l }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  </div>
</div>
{% endif %}
<!-- end, Table with FAIL results -->


<!-- begin, Table with WARNING results -->
{% if report_warning|length > 0%}
<div class="alert alert-warning" role="alert">
  <div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for l in report_warning %}
        <tr>
          <td>{{ l }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  </div>
</div>
{% endif %}
<!-- end, Table with WARNING results -->


<!-- begin, Table with PASS results -->
{% if report_pass|length > 0%}
<div class="alert alert-success" role="alert">
  <div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for l in report_pass %}
        <tr>
          <td>{{ l }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  </div>
</div>
{% endif %}
<!-- end, Table with PASS results -->



  <!-- begin, Foot -->
  <div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <a href="{% url 'inventories:ne_list' %}">Back to Inventory</a>
          <p></p>
          <a href="{% url 'inventories:ne_detail' ne_id %}">Back to {{ ne_fqdn }}</a>
        </td>
      </tr>
    </tbody>
  </table>
  </div>
  <!-- end, Foot -->


{% endblock content %}